--- Makefile	2004-03-21 19:44:18.000000000 +0200
+++ Makefile.new	2010-12-22 14:55:01.877826222 +0200
@@ -1,15 +1,15 @@
 # Makefile for chap
 # $Id: Makefile,v 1.5 2004/03/21 17:44:18 cnvogelg Exp $
 
-LIBDVDREAD=/soft/libdvdread
+LIBDVDREAD=/usr
 
 all: build
 
 build:
-	gcc -DNDEBUG -Wall -I$(LIBDVDREAD)/include -L$(LIBDVDREAD)/lib -ldvdread -Wl,-rpath,$(LIBDVDREAD)/lib -o chaplin chaplin.c -lm
+	gcc $(CFLAGS) -DNDEBUG -Wall -I$(LIBDVDREAD)/include -L$(LIBDVDREAD)/lib$(LIBDIRSUFFIX) -ldvdread -Wl,-rpath,$(LIBDVDREAD)/lib -o chaplin chaplin.c -lm
 
 debug:
-	gcc -Wall -I$(LIBDVDREAD)/include -L$(LIBDVDREAD)/lib -ldvdread -Wl,-rpath,$(LIBDVDREAD)/lib -o chaplin chaplin.c -lm
+	gcc $(CFLAGS) -Wall -I$(LIBDVDREAD)/include -L$(LIBDVDREAD)/lib$(LIBDIRSUFFIX) -ldvdread -Wl,-rpath,$(LIBDVDREAD)/lib -o chaplin chaplin.c -lm
 
 dist:
 	cd .. ; tar cvfz chaplin.tgz chaplin/Makefile chaplin/chaplin.c chaplin/chaplin-genmenu chaplin/chaplin
